- name: Redémarre le service SNMPD et s'assure qu'il est activé au démarrage
  systemd:
    name: snmpd
    state: restarted
    enabled: yes
    
- name: Redémarre le service NRPE (Nagios Remote Plugin Executor)
  systemd:
    name: nagios-nrpe-server
    state: restarted
    
- name: Recharge la configuration du pare-feu UFW
  command: ufw reload