- name: Met à jour le cache des paquets et effectue une mise à niveau de distribution
  apt:
    update_cache: yes
    upgrade: dist

- name: Installe le paquet Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx pour le backend en utilisant un template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'

- name: S'assure que Nginx est démarré et activé au démarrage
  service:
    name: nginx
    state: started
    enabled: yes

- name: Définit un fait local avec le numéro du serveur
  set_fact:
    local_server_number: "{{ server_number }}"

- name: Crée le fichier HTML du backend en utilisant un template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Recharge Nginx pour appliquer la nouvelle configuration
  service:
    name: nginx
    state: reloaded

- name: Installe les paquets requis et met à jour le cache des paquets
  apt:
    update_cache: yes
    name:
      - lsb-release
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - wget
      - gnupg2
      - curl
    state: present

- name: Met à jour le cache apt après l'ajout de nouveaux dépôts
  apt:
    update_cache: yes

- name: Récupère la première adresse IP du groupe de supervision
  set_fact:
    supervision_ip: "{{ groups['supervision'][1] }}"
  delegate_to: localhost
  run_once: true

- name: Installe les paquets SNMP et SNMPD, et met à jour le cache des paquets
  apt:
    name:
      - snmpd
      - snmp
    state: present
    update_cache: yes

- name: Configure SNMP avec les paramètres spécifiés
  copy:
    content: |
      agentAddress udp:161

      com2sec notConfigUser  {{ supervision_ip }}       publique

      group   notConfigGroup v1           notConfigUser
      group   notConfigGroup v2c          notConfigUser

      view systemview    included   .1.3.6.1.2.1.1
      view systemview    included   .1.3.6.1.2.1.25.1.1
      view systemview    included   .1.3.6.1.4.1.2021.4
      view systemview    included   .1.3.6.1.4.1.2021.11
      view systemview    included   .1.3.6.1.4.1.2021.9
      view systemview    included   .1.3.6.1.4.1.2021.10
      view systemview    included   .1.3.6.1.2.1.4
      view systemview    included   .1.3.6.1.2.1.6
      view systemview    included   .1.3.6.1.2.1.7
      view systemview    included   .1.3.6.1.2.1.2
      view systemview    included   .1.3.6.1.2.1.5
      view systemview    included   .1.3.6.1.2.1.25.2
      view systemview    included   .1.3.6.1.2.1.25.3
      view systemview    included   .1.3.6.1.2.1.25.4
      view systemview    included   .1.3.6.1.2.1.25.5
      view systemview    included   .1.3.6.1.2.1.25.6
      view systemview    included   .1.3.6.1.2.1.25.7
      view centreon      included   .1.3.6.1
      
      access notConfigGroup "" any noauth exact systemview none none
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart SNMPD

- name: S'assure que SNMPD est démarré et activé au démarrage
  service:
    name: snmpd
    state: started
    enabled: yes

- name: Installe UFW et met à jour le cache des paquets
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Autorise le port SSH via UFW
  ufw:
    rule: allow
    port: 22
    proto: tcp
    from: "{{ supervision_ip }}"

- name: Configure les règles UFW pour différents services Centreon
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from: "{{ supervision_ip }}"
  loop:
    - { port: '80', proto: 'tcp' }   # HTTP pour l'accès à l'interface web
    - { port: '443', proto: 'tcp' }  # HTTPS pour l'accès sécurisé à l'interface web
    - { port: '3306', proto: 'tcp' } # MySQL, si nécessaire pour Centreon SQL
    - { port: '5666', proto: 'tcp' } # NRPE pour les connexions Centreon supervisées
    - { port: '5667', proto: 'tcp' } # NSCA pour les données passives
    - { port: '5669', proto: 'tcp' } # Centreon Trap handling
    - { port: '162', proto: 'udp' }  # SNMP traps, si utilisé pour les alertes
    - { port: '161', proto: 'udp' }  # SNMP polling

- name: Active UFW et définit la politique par défaut sur deny
  ufw:
    state: enabled
    default: deny
  notify: reload ufw

- name: Vérifie l'état d'UFW en mode verbose
  command: ufw status verbose
  changed_when: false
  register: ufw_status

- name: Affiche le statut d'UFW
  debug:
    msg: "{{ ufw_status.stdout_lines }}"

- name: Installe le serveur NRPE et les plugins Nagios, et met à jour le cache des paquets
  apt:
    name:
      - nagios-nrpe-server
      - nagios-plugins
    state: present
    update_cache: yes

- name: Configure NRPE avec les paramètres spécifiés
  copy:
    content: |
      server_address=0.0.0.0
      allowed_hosts=127.0.0.1,{{ groups['supervision'][0] }}
      nrpe_user=nrpe
      nrpe_group=nrpe
      dont_blame_nrpe=0
      command_timeout=60
      connection_timeout=300
      include_dir=/etc/nagios/nrpe.d/
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart NRPE

- name: S'assure que NRPE est démarré et activé au démarrage
  systemd:
    name: nagios-nrpe-server
    state: started
    enabled: yes

- name: S'assure que le serveur SSH est installé et met à jour le cache des paquets
  apt:
    name: openssh-server
    state: present
    update_cache: yes

- name: S'assure que le service SSH est démarré et activé au démarrage
  systemd:
    name: ssh
    state: started
    enabled: yes

- name: Autorise SSH via UFW
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: S'assure que UFW est activé
  ufw:
    state: enabled

- name: Recharge UFW pour appliquer les modifications
  command: ufw reload

- name: Installe Java (OpenJDK 11) et met à jour le cache des paquets
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes