- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx for backend
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Set server number fact
  set_fact:
    local_server_number: "{{ server_number }}"

- name: Create backend HTML file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Recharger Nginx pour appliquer la configuration
  service:
    name: nginx
    state: reloaded

- name: Install required packages
  apt:
    update_cache: yes
    name:
      - lsb-release
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - wget
      - gnupg2
      - curl
    state: present

- name: Update apt cache after adding repositories
  apt:
    update_cache: yes

- name: Gather the first IP address from the supervision group
  set_fact:
    supervision_ip: "{{ groups['supervision'][1] }}"
  delegate_to: localhost
  run_once: true

- name: Install SNMP
  apt:
    name:
      - snmpd
      - snmp
    state: present
    update_cache: yes

- name: Configure SNMP
  copy:
    content: |
      agentAddress udp:161

      com2sec notConfigUser  {{ supervision_ip }}       publique

      group   notConfigGroup v1           notConfigUser
      group   notConfigGroup v2c          notConfigUser

      view systemview    included   .1.3.6.1.2.1.1
      view systemview    included   .1.3.6.1.2.1.25.1.1
      view systemview    included   .1.3.6.1.4.1.2021.4
      view systemview    included   .1.3.6.1.4.1.2021.11
      view systemview    included   .1.3.6.1.4.1.2021.9
      view systemview    included   .1.3.6.1.4.1.2021.10
      view systemview    included   .1.3.6.1.2.1.4
      view systemview    included   .1.3.6.1.2.1.6
      view systemview    included   .1.3.6.1.2.1.7
      view systemview    included   .1.3.6.1.2.1.2
      view systemview    included   .1.3.6.1.2.1.5
      view systemview    included   .1.3.6.1.2.1.25.2
      view systemview    included   .1.3.6.1.2.1.25.3
      view systemview    included   .1.3.6.1.2.1.25.4
      view systemview    included   .1.3.6.1.2.1.25.5
      view systemview    included   .1.3.6.1.2.1.25.6
      view systemview    included   .1.3.6.1.2.1.25.7
      view centreon      included   .1.3.6.1
      
      access notConfigGroup "" any noauth exact systemview none none
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart SNMPD

- name: Ensure SNMPD is started and enabled
  service:
    name: snmpd
    state: started
    enabled: yes


- name: Installation de UFW
  apt:
    name: ufw
    state: present
    update_cache: yes  # Assurez-vous que le cache des paquets est à jour

- name: Autoriser SSH
  ufw:
    rule: allow
    port: 22
    proto: tcp
    from: "{{ supervision_ip }}"

- name: Configuration des règles UFW pour Centreon
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from: "{{ supervision_ip }}"
  loop:
    - { port: '80', proto: 'tcp' }   # HTTP pour l'accès à l'interface web
    - { port: '443', proto: 'tcp' }  # HTTPS pour l'accès sécurisé à l'interface web
    - { port: '3306', proto: 'tcp' } # MySQL, si nécessaire pour Centreon SQL
    - { port: '5666', proto: 'tcp' } # NRPE pour les connexions Centreon supervisées
    - { port: '5667', proto: 'tcp' } # NSCA pour les données passives
    - { port: '5669', proto: 'tcp' } # Centreon Trap handling
    - { port: '162', proto: 'udp' }  # SNMP traps, si utilisé pour les alertes
    - { port: '161', proto: 'udp' }  # SNMP polling

- name: Activation de UFW
  ufw:
    state: enabled
    default: deny
  notify: reload ufw

- name: Vérification de l'état de UFW
  command: ufw status verbose
  changed_when: false
  register: ufw_status

- name: Afficher le statut de UFW
  debug:
    msg: "{{ ufw_status.stdout_lines }}"


- name: Install NRPE and Nagios plugins
  apt:
    name:
      - nagios-nrpe-server
      - nagios-plugins
    state: present
    update_cache: yes

- name: Configure NRPE
  copy:
    content: |
      server_address=0.0.0.0
      allowed_hosts=127.0.0.1,{{ groups['supervision'][0] }}
      nrpe_user=nrpe
      nrpe_group=nrpe
      dont_blame_nrpe=0
      command_timeout=60
      connection_timeout=300
      include_dir=/etc/nagios/nrpe.d/
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart NRPE

- name: Ensure NRPE is started and enabled
  systemd:
    name: nagios-nrpe-server
    state: started
    enabled: yes

- name: Ensure SSH is installed
  apt:
    name: openssh-server
    state: present
    update_cache: yes

- name: Ensure SSH service is enabled and started
  systemd:
    name: ssh
    state: started
    enabled: yes

- name: Allow SSH through UFW
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Ensure UFW is enabled
  ufw:
    state: enabled

- name: Reload UFW to apply changes
  command: ufw reload

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes