- name: Met à jour le cache des paquets et effectue une mise à niveau de distribution
  apt:
    update_cache: yes
    upgrade: dist

- name: Installe et configure MariaDB en utilisant le rôle bertvv.mariadb
  include_role:
    name: bertvv.mariadb
  vars:
    mariadb_daemon_user: mysql
    mariadb_daemon_user_uid: false
    mariadb_root_password: "root"
    mariadb_databases:
      - name: RestoProch
        collation: utf8_general_ci
    mariadb_users:
      - name: root
        password: root
        priv: "RestoProch.*:ALL"

- name: S'assure que les répertoires MariaDB ont les bons propriétaires et permissions
  file:
    path: "{{ item }}"
    owner: mysql
    group: mysql
    recurse: yes
  with_items:
    - /var/lib/mysql
    - /etc/mysql
    - /var/log/mysql

- name: Démarre et active le service MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Crée le script de sauvegarde en utilisant un template
  template:
    src: snapshot_db.sh.j2
    dest: /usr/local/bin/snapshot_db.sh
    mode: '0755'

- name: Ajoute une tâche cron pour la sauvegarde automatique de la base de données
  cron:
    name: "Sauvegarde automatique de la base de données"
    minute: 0
    hour: "*/12"
    user: root
    job: "/usr/local/bin/snapshot_db.sh"
